parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''
    api_platform.metadata_cache: true

api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
        pagination:
            items_per_page: '%env(int:ITEMS_PER_PAGE)%'
            client_items_per_page: true
    version: '1.0.11'
    formats:
        jsonld:   ['application/ld+json']
        html:     ['text/html']
    http_cache:
      invalidation:
        enabled: true
        varnish_urls: ['%env(VARNISH_URL)%']
      # Adds sensitive default cache headers
      max_age: 0
      shared_max_age: 3600
      vary: ['Content-Type', 'Authorization']
      public: true